local M = {}

local function style(config, name)
  return config.styles[name] or {}
end

function M.setup(c, config)
  local h = {
    Normal = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.surface },
    NormalNC = { fg = c.fg, bg = c.bg },
    FloatBorder = { fg = c.border_strong, bg = c.surface },
    FloatTitle = { fg = c.fg_bright, bg = c.surface, bold = true },
    ColorColumn = { bg = c.surface },
    Conceal = { fg = c.fg_muted },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorColumn = { bg = c.cursor_line },
    CursorLine = { bg = c.cursor_line },
    CursorLineNr = { fg = c.white, bold = true },
    LineNr = { fg = c.gutter },
    SignColumn = { fg = c.fg_muted, bg = c.bg },
    FoldColumn = { fg = c.fg_muted, bg = c.bg },
    Folded = { fg = c.fg_muted, bg = c.surface },
    VertSplit = { fg = c.border },
    WinSeparator = { fg = c.border },
    StatusLine = { fg = c.fg_emphasis, bg = c.surface },
    StatusLineNC = { fg = c.fg_muted, bg = c.surface },
    TabLine = { fg = c.fg_muted, bg = c.surface },
    TabLineFill = { bg = c.bg },
    TabLineSel = { fg = c.white, bg = c.surface_active, bold = true },
    Pmenu = { fg = c.fg, bg = c.surface },
    PmenuSel = { fg = c.fg_bright, bg = c.surface_active, bold = true },
    PmenuSbar = { bg = c.surface_active },
    PmenuThumb = { bg = c.border_strong },
    Visual = { bg = c.selection },
    VisualNOS = { bg = c.selection },
    Search = { fg = c.search_fg, bg = c.search_bg },
    IncSearch = { fg = c.bg, bg = c.fg_bright },
    CurSearch = { fg = c.bg, bg = c.fg_bright },
    MatchParen = { fg = c.white, bg = c.match, bold = true },
    Directory = { fg = c.blue },
    Title = { fg = c.white, bold = true },
    Question = { fg = c.green },
    MoreMsg = { fg = c.green },
    ModeMsg = { fg = c.fg_bright, bold = true },
    WarningMsg = { fg = c.yellow },
    ErrorMsg = { fg = c.red },
    Error = { fg = c.red },
    WildMenu = { fg = c.white, bg = c.surface_active },
    NonText = { fg = c.fg_disabled },
    SpecialKey = { fg = c.fg_disabled },
    Whitespace = { fg = c.fg_disabled },
    EndOfBuffer = { fg = c.bg },
    QuickFixLine = { bg = c.surface_hover, bold = true },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.blue, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },

    Comment = vim.tbl_extend("force", { fg = c.fg_muted }, style(config, "comments")),
    -- Keep code syntax grayscale; accent colors are reserved for diagnostics, Git, diffs, and terminal ANSI roles.
    Constant = { fg = c.fg },
    String = { fg = c.fg },
    Character = { fg = c.fg },
    Number = { fg = c.fg },
    Boolean = { fg = c.fg },
    Float = { fg = c.fg },
    Identifier = vim.tbl_extend("force", { fg = c.fg }, style(config, "variables")),
    Function = vim.tbl_extend("force", { fg = c.fg_bright }, style(config, "functions")),
    Statement = vim.tbl_extend("force", { fg = c.fg_emphasis }, style(config, "keywords")),
    Conditional = { fg = c.fg_emphasis },
    Repeat = { fg = c.fg_emphasis },
    Label = { fg = c.fg_emphasis },
    Operator = { fg = c.fg },
    Keyword = vim.tbl_extend("force", { fg = c.fg_emphasis }, style(config, "keywords")),
    Exception = { fg = c.fg_emphasis },
    PreProc = { fg = c.fg_emphasis },
    Include = { fg = c.fg_emphasis },
    Define = { fg = c.fg_emphasis },
    Macro = { fg = c.fg_emphasis },
    PreCondit = { fg = c.fg_emphasis },
    Type = { fg = c.fg_bright },
    StorageClass = { fg = c.fg_emphasis },
    Structure = { fg = c.fg_emphasis },
    Typedef = { fg = c.fg_bright },
    Special = { fg = c.fg },
    SpecialChar = { fg = c.fg },
    Tag = { fg = c.fg },
    Delimiter = { fg = c.fg_muted },
    Debug = { fg = c.fg_muted },
    Underlined = { fg = c.fg_bright, underline = true },
    Ignore = { fg = c.fg_disabled },
    Todo = { fg = c.fg_bright, bg = c.surface_active, bold = true },

    DiffAdd = { bg = c.git_add_bg },
    DiffChange = { bg = c.git_change_bg },
    DiffDelete = { fg = c.git_delete, bg = c.git_delete_bg },
    DiffText = { bg = c.surface_active },
    Added = { fg = c.green },
    Changed = { fg = c.blue },
    Removed = { fg = c.red },
    GitSignsAdd = { fg = c.git_add },
    GitSignsChange = { fg = c.git_change },
    GitSignsDelete = { fg = c.git_delete },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
    LspReferenceText = { bg = c.surface_hover },
    LspReferenceRead = { bg = c.surface_hover },
    LspReferenceWrite = { bg = c.surface_active },

    ["@comment"] = { link = "Comment" },
    ["@string"] = { link = "String" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@function"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.builtin"] = { link = "Function" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.return"] = { fg = c.fg_emphasis },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.fg_bright },
    ["@variable"] = { link = "Identifier" },
    ["@variable.parameter"] = { fg = c.fg },
    ["@property"] = { fg = c.fg },
    ["@field"] = { fg = c.fg },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.fg },
    ["@tag"] = { fg = c.fg },
    ["@tag.attribute"] = { fg = c.fg_emphasis },
    ["@tag.delimiter"] = { fg = c.fg_muted },
    ["@markup.heading"] = { fg = c.white, bold = true },
    ["@markup.link"] = { fg = c.fg_bright, underline = true },
    ["@markup.raw"] = { fg = c.fg },
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { fg = c.fg },
    ["@lsp.type.interface"] = { link = "Type" },
    -- Defer variable roles to Tree-sitter. An empty semantic-token group lets
    -- captures such as @variable, @variable.parameter, and @property retain
    -- their more specific styling instead of being flattened to c.fg.
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.variable"] = {},

    TelescopeNormal = { fg = c.fg, bg = c.surface },
    TelescopeBorder = { fg = c.border_strong, bg = c.surface },
    TelescopeSelection = { bg = c.surface_active, bold = true },
    TelescopeMatching = { fg = c.white, bold = true },
    TelescopePromptNormal = { fg = c.fg, bg = c.surface_hover },
    TelescopePromptBorder = { fg = c.border_strong, bg = c.surface_hover },
    TelescopePromptTitle = { fg = c.bg, bg = c.fg_bright, bold = true },
    WhichKey = { fg = c.fg_bright },
    WhichKeyGroup = { fg = c.fg_muted },
    WhichKeyDesc = { fg = c.fg },
    WhichKeyFloat = { bg = c.surface },
    LazyNormal = { fg = c.fg, bg = c.surface },
    LazyButton = { fg = c.fg, bg = c.surface_hover },
    LazyButtonActive = { fg = c.white, bg = c.surface_active, bold = true },
    LazyH1 = { fg = c.white, bg = c.surface_active, bold = true },
    SnacksPicker = { fg = c.fg, bg = c.surface },
    SnacksPickerBorder = { fg = c.border_strong, bg = c.surface },
    SnacksPickerInput = { fg = c.fg, bg = c.surface_hover },
    SnacksPickerInputBorder = { fg = c.border_strong, bg = c.surface_hover },
    SnacksPickerInputTitle = { fg = c.fg_bright, bg = c.surface_hover, bold = true },
    SnacksPickerBoxTitle = { fg = c.fg_bright, bg = c.surface, bold = true },
    SnacksPickerMatch = { fg = c.white, bold = true },
    NoiceCmdlinePopup = { fg = c.fg, bg = c.surface },
    NoiceCmdlinePopupBorder = { fg = c.border_strong, bg = c.surface },
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder = { fg = c.yellow },
    NotifyINFOBorder = { fg = c.blue },
    NotifyDEBUGBorder = { fg = c.fg_muted },
    NotifyTRACEBorder = { fg = c.cyan },
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrMatch = { fg = c.white, bold = true },
    CmpItemKind = { fg = c.blue },
    NeoTreeNormal = { fg = c.fg, bg = c.bg },
    NeoTreeNormalNC = { fg = c.fg, bg = c.bg },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeGitAdded = { fg = c.green },
    NeoTreeGitModified = { fg = c.yellow },
    NeoTreeGitDeleted = { fg = c.red },
    BufferLineFill = { bg = c.bg },
    BufferLineBackground = { fg = c.fg_muted, bg = c.surface },
    BufferLineBufferSelected = { fg = c.white, bg = c.surface_active, bold = true },

    -- Remaining built-in UI, LSP and legacy syntax groups.
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    LineNrAbove = { link = "LineNr" },
    LineNrBelow = { link = "LineNr" },
    MsgArea = { fg = c.fg },
    MsgSeparator = { fg = c.border },
    Substitute = { fg = c.bg, bg = c.fg_bright },
    PmenuMatch = { fg = c.white, bg = c.surface },
    PmenuMatchSel = { fg = c.white, bg = c.surface_active, bold = true },
    WinBar = { link = "StatusLine" },
    WinBarNC = { link = "StatusLineNC" },
    Bold = { fg = c.fg, bold = true },
    Italic = { fg = c.fg, italic = true },
    DiagnosticUnnecessary = { fg = c.fg_disabled },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.red_bg },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.yellow_bg },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.blue_bg },
    DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.blue_bg },
    LspSignatureActiveParameter = { bg = c.surface_active, bold = true },
    LspCodeLens = { fg = c.debug },
    LspInlayHint = { fg = c.fg_muted, bg = c.surface },
    LspInfoBorder = { link = "FloatBorder" },
    healthError = { link = "DiagnosticError" },
    healthSuccess = { link = "DiagnosticOk" },
    healthWarning = { link = "DiagnosticWarn" },
    diffAdded = { fg = c.green, bg = c.green_bg },
    diffRemoved = { fg = c.red, bg = c.red_bg },
    diffChanged = { fg = c.blue, bg = c.blue_bg },
    diffOldFile = { fg = c.blue },
    diffNewFile = { fg = c.blue },
    diffFile = { fg = c.blue },
    diffLine = { fg = c.fg_muted },
    diffIndexLine = { fg = c.fg_emphasis },
    qfFileName = { fg = c.blue },
    qfLineNr = { fg = c.fg_muted },
    helpCommand = { fg = c.blue, bg = c.surface },
    helpExample = { fg = c.fg_muted },

    -- Tree-sitter captures not covered by their Vim equivalents.
    ["@annotation"] = { link = "PreProc" },
    ["@attribute"] = { link = "PreProc" },
    ["@character"] = { link = "Character" },
    ["@character.printf"] = { link = "SpecialChar" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@comment.error"] = { fg = c.fg_muted },
    ["@comment.warning"] = { fg = c.fg_muted },
    ["@comment.note"] = { fg = c.fg_muted },
    ["@comment.info"] = { fg = c.fg_muted },
    ["@comment.hint"] = { fg = c.fg_muted },
    ["@comment.todo"] = { link = "Todo" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@constructor"] = { fg = c.fg_bright },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Function" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@label"] = { fg = c.fg_emphasis },
    ["@module"] = { link = "Include" },
    ["@module.builtin"] = { fg = c.fg_emphasis },
    ["@namespace.builtin"] = { link = "@module.builtin" },
    ["@punctuation.bracket"] = { fg = c.fg_muted },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.special"] = { fg = c.fg_muted },
    ["@string.documentation"] = { fg = c.fg },
    ["@string.escape"] = { fg = c.fg },
    ["@string.regexp"] = { fg = c.fg },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Keyword" },
    ["@variable.builtin"] = { fg = c.fg_emphasis },
    ["@variable.member"] = { fg = c.fg },
    ["@variable.parameter.builtin"] = { fg = c.fg },
    ["@markup.emphasis"] = { italic = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.link.label.symbol"] = { link = "Identifier" },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@markup.list"] = { fg = c.fg_emphasis },
    ["@markup.list.checked"] = { fg = c.fg },
    ["@markup.list.unchecked"] = { fg = c.fg_muted },
    ["@markup.math"] = { link = "Special" },
    ["@markup.raw.markdown_inline"] = { fg = c.fg, bg = c.surface },

    -- LSP semantic-token aliases and completion kind groups.
    ["@lsp.type.boolean"] = { link = "@boolean" },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
    ["@lsp.type.selfTypeKeyword"] = { link = "@variable.builtin" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.typeAlias"] = { link = "@type.definition" },
    ["@lsp.type.unresolvedReference"] = { sp = c.red, undercurl = true },
    ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.callable"] = { link = "@function" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.static"] = { link = "@constant" },
    ["@lsp.kind.class"] = { link = "Type" },
    ["@lsp.kind.function"] = { link = "Function" },
    ["@lsp.kind.method"] = { link = "Function" },
    ["@lsp.kind.variable"] = { link = "Identifier" },
    ["@lsp.kind.property"] = { link = "Identifier" },
    ["@lsp.kind.keyword"] = { link = "Keyword" },
    ["@lsp.kind.string"] = { link = "String" },
    ["@lsp.kind.number"] = { link = "Number" },

    -- LazyVim's default UI plugins.
    TroubleNormal = { fg = c.fg, bg = c.bg },
    TroubleNormalNC = { fg = c.fg, bg = c.bg },
    TroubleText = { fg = c.fg },
    TroubleCount = { fg = c.fg_bright, bg = c.surface_active },
    TroubleIndent = { fg = c.fg_disabled },
    TroubleSource = { fg = c.fg_muted },
    FlashLabel = { fg = c.bg, bg = c.fg_bright, bold = true },
    FlashMatch = { fg = c.white, bg = c.surface_active },
    FlashCurrent = { fg = c.bg, bg = c.yellow, bold = true },
    IlluminatedWordText = { bg = c.surface_hover },
    IlluminatedWordRead = { bg = c.surface_hover },
    IlluminatedWordWrite = { bg = c.surface_active },
    IndentBlanklineChar = { fg = c.border },
    IndentBlanklineContextChar = { fg = c.fg_muted },
    IblIndent = { fg = c.border },
    IblScope = { fg = c.fg_muted },
    NavicText = { fg = c.fg_muted },
    NavicSeparator = { fg = c.fg_disabled },
    NavicIconsFile = { fg = c.blue },
    DashboardHeader = { fg = c.fg_bright },
    DashboardFooter = { fg = c.fg_muted },
    DashboardDesc = { fg = c.fg },
    DashboardKey = { fg = c.blue },
    AlphaHeader = { fg = c.fg_bright },
    AlphaFooter = { fg = c.fg_muted },
    AlphaButtons = { fg = c.fg },
    RenderMarkdownCode = { bg = c.surface },
    RenderMarkdownCodeInfo = { bg = c.blue_bg },
    RenderMarkdownCodeWarn = { bg = c.yellow_bg },
    RenderMarkdownCodeError = { bg = c.red_bg },
    RenderMarkdownH1 = { fg = c.white, bold = true },
    RenderMarkdownH2 = { fg = c.fg_bright, bold = true },
  }

  if config.on_highlights then
    config.on_highlights(h, c)
  end
  return h
end

return M
